#cloud-config
timezone: ${timezone}

repo_update: true
repo_upgrade: all

packages:
  - git

runcmd:
  - git clone --depth=1 https://github.com/lluked/manuka /home/ubuntu/manuka
  - cd /home/ubuntu/manuka
  - ./bin/setup.sh auto
  - usermod -aG docker ubuntu
  - htpasswd -bc /opt/manuka/docker/traefik/etc/conf/traefik.htpasswd ${traefikUser} ${traefikPassword}
  - htpasswd -bc /opt/manuka/docker/traefik/etc/conf/kibana.htpasswd ${kibanaUser} ${kibanaPassword}
  - shutdown -r now