version: '3.8'
# Services
services:
    # Kibana Service
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - $baseDir/docker/elastic/kibana/share/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    # ports:
    #   - "5601:5601"
    networks:
      - elastic