version: '3.8'
# Services
services:
  # Logstash Service
  logstash:
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    env_file:
      - $baseDir/ip.env
    volumes:
      - $baseDir/docker/elastic/logstash/share/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - $baseDir/docker/elastic/logstash/share/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - $baseDir/docker/elastic/logstash/share/pipeline:/usr/share/logstash/pipeline:ro
      - $baseDir/docker/elastic/logstash/share/db:/usr/share/logstash/db:ro
      - $baseDir/mnt/var/log:/logs:ro
    ports:
      - "5044:5044"
      - "9600:9600"
      - "9700:9700"
    networks:
      - elastic